# Generated by Django 3.2.12 on 2023-08-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cseStud', '0002_alter_csestud_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csestud',
            name='DOB',
            field=models.DateField(verbose_name='%d/%m/%y'),
        ),
    ]
