# Generated by Django 4.2.4 on 2023-08-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cseStud', '0003_alter_csestud_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csestud',
            name='FirstGraduate',
        ),
        migrations.RemoveField(
            model_name='csestud',
            name='Pending',
        ),
        migrations.AlterField(
            model_name='csestud',
            name='DOB',
            field=models.DateField(),
        ),
    ]
