# Generated by Django 4.2.4 on 2023-10-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eceStud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerNo', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('rollno', models.CharField(blank=True, default=None, max_length=7, null=True)),
                ('Year', models.IntegerField(blank=True, default=None, null=True)),
                ('Class', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('DOB', models.DateField(blank=True, default=None, null=True)),
                ('Place', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('YearOfJoin', models.IntegerField(blank=True, default=None, null=True)),
                ('Languages', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('FatherName', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('FathersOccupation', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('MotherName', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('MothersOccupation', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Fees', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='eceStud2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerNo', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('rollno', models.CharField(blank=True, default=None, max_length=7, null=True)),
                ('Year', models.IntegerField(blank=True, default=None, null=True)),
                ('Class', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('DOB', models.DateField(blank=True, default=None, null=True)),
                ('Place', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('YearOfJoin', models.IntegerField(blank=True, default=None, null=True)),
                ('Languages', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('FatherName', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('FathersOccupation', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('MotherName', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('MothersOccupation', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Fees', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='eceStud3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerNo', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('rollno', models.CharField(blank=True, default=None, max_length=7, null=True)),
                ('Year', models.IntegerField(blank=True, default=None, null=True)),
                ('Class', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('DOB', models.DateField(blank=True, default=None, null=True)),
                ('Place', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('YearOfJoin', models.IntegerField(blank=True, default=None, null=True)),
                ('Languages', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('FatherName', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('FathersOccupation', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('MotherName', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('MothersOccupation', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Fees', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='eceStud4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerNo', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('rollno', models.CharField(blank=True, default=None, max_length=7, null=True)),
                ('Year', models.IntegerField(blank=True, default=None, null=True)),
                ('Class', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('DOB', models.DateField(blank=True, default=None, null=True)),
                ('Place', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('YearOfJoin', models.IntegerField(blank=True, default=None, null=True)),
                ('Languages', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('FatherName', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('FathersOccupation', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('MotherName', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('MothersOccupation', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Fees', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
