# Generated by Django 4.2.4 on 2023-10-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eeeStud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='eceStud2',
            new_name='eeeStud',
        ),
        migrations.RenameModel(
            old_name='eceStud4',
            new_name='eeeStud2',
        ),
        migrations.RenameModel(
            old_name='eceStud3',
            new_name='eeeStud3',
        ),
        migrations.RenameModel(
            old_name='eceStud',
            new_name='eeeStud4',
        ),
    ]
